# tasks/_combine_mw_user_authorized_keys.yml
---
-
  name: Retrieve {{ username }} ssh pub key
  include_tasks: _retrieve_username_pubkey.yml

-
  name: Add pub keys into grouped authorized_keys
  set_fact:
    mw_authorized_keys: '{{ mw_authorized_keys + authorized_keys }}'
