---
- name: Get Mikroways Users from remote URL
  set_fact:
    remote_users: "{{ lookup('url', mw_user_url, wantlist=True) }}"
    valid_users: []

- name: Validate remote Users
  set_fact:
    valid_users: "{{ valid_users  + [item] }}"
  when: item is regex("^[a-z_]([a-z0-9_-]{0,31}|[a-z0-9_-]{0,30}\$)$")
  loop: "{{ remote_users }}"

- name: Validate remote users is not empty
  fail:
    msg: There are no valid users retrieved from {{ mw_user_url }}
  when: valid_users | length == 0

- name: Create only named users
  set_fact:
    mw_user_valid_users: "{{ mw_user_enabled_users | intersect(valid_users) }}"
  when: mw_user_enabled_users | length > 0

- name: Create only named users
  set_fact:
    mw_user_valid_users: "{{ valid_users }}"
  when: mw_user_enabled_users | length == 0

- name: Prepare users
  block:
    -
      name: Initialize variable mgm_user_list
      set_fact:
        mgm_user_list: []
    -
      name: Create common user {{ mw_user_name }}
      include: _prepare_mw_user.yml
    -
      name: Populate users in mgm_user_list
      include: _prepare_user.yml
      vars:
        username: "{{ current_user }}"
      loop: "{{ mw_user_valid_users }}"
      loop_control:
        loop_var: current_user
      when: mw_user_create_one_account_per_user

- name: Create users with role grog.management-user
  import_role:
    name: grog.management-user
  become: true
  vars:
    management_user_list: "{{ mgm_user_list }}"
