# tasks/main.yml
---

# Execute Mikroways user tasks
- name: Include Mikroways user configuration
  include_tasks: _mw_configuration.yml
  when: add_mw_accounts | bool

# Conditionally include client user tasks
- name: Include client user configuration
  include_tasks: _client_configuration.yml
  when: add_client_accounts | bool
