---
dependency:
  name: galaxy
  options:
    role-file: meta/requirements.yml
driver:
  name: docker
platforms:
  - name: mw-user-one-user
    image: ubuntu:20.04
  - name: mw-user-multiple-users
    image: ubuntu:20.04
    groups:
      - multiple_users
  - name: mw-user-select-users-one-user
    image: ubuntu:20.04
    groups:
      - select_users
  - name: mw-user-select-users-multiple-users
    image: ubuntu:20.04
    groups:
      - select_users
      - multiple_users
provisioner:
  name: ansible
  inventory:
    group_vars:
      multiple_users:
        mw_user_create_one_account_per_user: true
      select_users:
        mw_user_enabled_users:
          - car
          - leandro
    host_vars:
      all:
        ansible_user: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
