---
# This is an example playbook to execute Ansible tests.

- name: Verify mw_user is always created
  hosts: all
  gather_facts: false
  vars:
    mw_user_name: mikroways
    mw_user_url: https://mikroways.gitlab.io/public/ssh_keys/_users
  tasks:
    -
      name: Verify user {{ mw_user_name }} is created
      command: "id {{ mw_user_name }}"
      changed_when: false
    -
      name: Verify all users are created
      command: "id {{ item }}"
      changed_when: false
      when: inventory_hostname in groups['multiple_users'] and
        inventory_hostname not in groups['select_users']
      loop: "{{ lookup('url', mw_user_url, wantlist=True) }}"
    -
      name: Verify selected users are created
      command: "id {{ item }}"
      changed_when: false
      when: inventory_hostname in groups['multiple_users'] and
        inventory_hostname in groups['select_users']
      loop: "{{ mw_user_enabled_users }}"
