name: Release to Ansible Galaxy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  galaxy_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install ansible-galaxy CLI
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Publish to Galaxy
        run: ansible-galaxy role import mikroways mw_user --github-token ${{ secrets.GITHUB_TOKEN }}

