dependency:
  name: galaxy
  options:
    role-file: meta/requirements.yml
driver:
  name: docker
platforms:
  - name: client-admin-only
    image: ubuntu:20.04
    groups:
      - admin_only
    pre_build_image: false
    dockerfile: Dockerfile.j2
  - name: client-multiple-users
    image: ubuntu:20.04
    groups:
      - multiple_users
    pre_build_image: false
    dockerfile: Dockerfile.j2
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      admin_only:
        client_user_create_one_account_per_user: false
        client_ssh_key_directory: "/etc/ansible/files/client_ssh_keys"
      multiple_users:
        client_user_create_one_account_per_user: true
        client_ssh_key_directory: "/etc/ansible/files/client_ssh_keys"
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
